# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests
on: [push, pull_request, create]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11' ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pytest coverage pytest-cov -U
        pip install -v .
    - name: Test Testable Components
      run: |
        # All other tests depend upon fixture data not stored with the repository
        echo "generating a data file sufficient to extend past 1 member"
        curl -o test/data/sample.txt  http://textfiles.com/stories/bureau.txt
        seq 30000 | xargs -P1 -n1 -I@ cat test/data/sample.txt >> test/data/large.txt
        python idzip/command.py test/data/large.txt
        cd test
        pytest -l -s -v test_high_level_api.py --cov-report term
        cd ..
        rm -f test/data/large.txt.dz test/data/sample.txt.dz

